name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        options:
        - staging
        - production
      version:
        type: string
        description: Release Version
      hash:
        type: string
        description: Artifact Hash
      app:
        type: choice
        description: App
        options:
        - ./infrastructure/operations-portal
        - ./infrastructure/scheduler

# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}

jobs:
  build:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }}"
          echo "version is ${{ github.event.inputs.version }}"
          echo "hash is ${{ github.event.inputs.hash }}"
          echo "app is ${{ github.event.inputs.app }}"
        
  pre-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: backend and provider config
        working-directory: ${{ github.event.inputs.app }}
        run: |
          pwd
          ls -la
          cat backend.tf
          rm backend.tf
          rm provider.tf
          ls -la
          echo "writing secrets to backend step"
          echo "${{secrets.BACKEND}}" > backend.tf
          cat backend.tf
          echo "${{secrets.PROVIDER}}" > provider.tf
          cat provider.tf

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-skip-session-tagging: true
      #     aws-region: us-east-1
      #     role-duration-seconds: 900
      #     role-to-assume: arn:aws:iam::CHANGEACCOUNT:role/iam_github_actions
